# my global config
global:
  scrape_interval:     60s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  # my cassandra nodes - node_exporter_metrics - provide IPs for all nodes
  - job_name: 'node_exporter_metrics'
    scrape_interval: 180s
    static_configs:
    # - targets: ['<SERVER1_IP_OR_HOSTNAME>:9100', '<SERVER2_IP_OR_HOSTNAME>:9100', '<SERVER3_IP_OR_HOSTNAME>:9100', ...]
    - targets: ['192.168.1.151:9100', '192.168.1.152:9100', '192.168.1.153:9100']


